-- runtime/globals.lua — single accessor surface for the scalar
-- `wezterm.GLOBAL.wezsesh_*` keys.
--
-- wezterm.GLOBAL is a userdata that snapshots-on-read and replaces-on-
-- write; it survives the `package.loaded["wezsesh.*"]` cache-bust loop
-- that init.lua runs on Ctrl+Shift+R reload, which is exactly why we
-- park process-scoped values there. Three scalar keys live under this
-- module's authority:
--
--   wezsesh_session_key    — 64 lowercase hex chars; the HMAC key
--                            shared between the binary and the plugin.
--                            Generated by `manager.ensure_session_key`
--                            at apply_to_config time.
--   wezsesh_bin_path       — absolute path to the wezsesh binary.
--                            Written by init.lua step 6 so the reply
--                            spawn (`result.lua`) can shell out without
--                            re-resolving the binary every call.
--   wezsesh_plugin_version — semver string. Used by the
--                            wipe-on-version-mismatch loop to clear
--                            every `wezsesh_*` GLOBAL key when the
--                            plugin version changes (downgrade, first
--                            load, upgrade), keeping new code from
--                            reading old-shaped values.
--
-- Per-pane state buckets (`wezsesh_state`, `wezsesh_seen_ids`) live in
-- `runtime.state`, the second authorised accessor for the GLOBAL
-- surface. The lualint rule `lua-globals-only` enforces that no other
-- file touches `wezterm.GLOBAL.wezsesh_*` directly.
--
-- Validation: accessors are thin wrappers. Callers validate the read
-- value's shape (e.g. ipc.lua's HMAC key length check, manager.lua's
-- semver parser) so the error context is local to the caller.

local wezterm = require("wezterm")

local M = {}

-- ────────────────────────────────────────────────────────────────────
-- session_key — wezsesh_session_key (HMAC key, 64 hex chars)
-- ────────────────────────────────────────────────────────────────────

function M.session_key()
    return wezterm.GLOBAL.wezsesh_session_key
end

function M.set_session_key(hex)
    wezterm.GLOBAL.wezsesh_session_key = hex
end

-- ────────────────────────────────────────────────────────────────────
-- bin_path — wezsesh_bin_path (absolute binary path)
-- ────────────────────────────────────────────────────────────────────

function M.bin_path()
    return wezterm.GLOBAL.wezsesh_bin_path
end

function M.set_bin_path(p)
    wezterm.GLOBAL.wezsesh_bin_path = p
end

-- ────────────────────────────────────────────────────────────────────
-- plugin_version — wezsesh_plugin_version (semver stamp)
-- ────────────────────────────────────────────────────────────────────

function M.plugin_version()
    return wezterm.GLOBAL.wezsesh_plugin_version
end

function M.set_plugin_version(v)
    wezterm.GLOBAL.wezsesh_plugin_version = v
end

-- ────────────────────────────────────────────────────────────────────
-- wipe_on_version_mismatch
-- ────────────────────────────────────────────────────────────────────
--
-- Compares the stored `wezsesh_plugin_version` GLOBAL stamp to the
-- supplied `version`. On match, returns immediately. On mismatch (nil
-- first-load, downgrade, upgrade) every `wezsesh_*` GLOBAL key is
-- cleared before the new stamp is written — without the wipe, a
-- shape-changing release would have new code reading old-shaped
-- values and crashing on the indexing path.
--
-- MUST run BEFORE any other GLOBAL write or listener registration in
-- apply_to_config — otherwise the wipe nukes the writes.
--
-- `pairs(wezterm.GLOBAL)` is iterable in production wezterm (the
-- userdata implements __pairs); the spec harness installs a __pairs
-- metamethod on its proxy so this enumeration works under tests.

function M.wipe_on_version_mismatch(version)
    local stored = wezterm.GLOBAL.wezsesh_plugin_version
    if stored == version then return end
    local doomed = {}
    for k, _ in pairs(wezterm.GLOBAL) do
        if type(k) == "string" and k:sub(1, 8) == "wezsesh_" then
            doomed[#doomed + 1] = k
        end
    end
    for _, k in ipairs(doomed) do
        wezterm.GLOBAL[k] = nil
    end
    wezterm.GLOBAL.wezsesh_plugin_version = version
end

return M
