// codegen produces plugin/wezsesh/default_allowlist.lua from
// internal/argvallow/default.txt. The output is fixed by §9.12 — the
// CI freshness gate (§17.4 "Argv default list sync") regenerates and
// diff-checks against the committed file.
//
//	go run ./internal/argvallow/codegen           # write to stdout
//	go run ./internal/argvallow/codegen -o <file> # write to file
//	go run ./internal/argvallow/codegen --check <file>
//	    # exit 1 if <file> differs from the expected output
//
// The grouping (shells / editors / pagers / vcs / langs / monitors /
// multiplexers) is a property of THIS codegen tool, not default.txt:
// default.txt is unadorned (one entry per line). Reordering or
// extending default.txt past the 35-entry / 7-group layout requires
// updating the boundaries array below AND the §9.12 example.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/Grady-Saccullo/wezsesh/internal/argvallow"
)

// groupBoundaries is the cumulative index after each group, matching
// the §9.12 layout: 6 shells, 7 editors, 4 pagers, 4 vcs, 7 langs,
// 5 monitors, 2 multiplexers.
var groupBoundaries = []int{6, 13, 17, 21, 28, 33, 35}

const (
	headerLine1 = "-- AUTOGENERATED by `go run ./internal/argvallow/codegen`."
	headerLine2 = "-- Source: internal/argvallow/default.txt"
	headerLine3 = "-- DO NOT EDIT BY HAND."
)

func main() {
	var (
		outPath   string
		checkPath string
	)
	flag.StringVar(&outPath, "o", "", "write output to this file (default: stdout)")
	flag.StringVar(&checkPath, "check", "", "compare existing file to expected output; exit 1 on mismatch")
	flag.Parse()

	expected, err := render(argvallow.Default())
	if err != nil {
		fmt.Fprintf(os.Stderr, "codegen: render: %v\n", err)
		os.Exit(2)
	}

	if checkPath != "" {
		got, err := os.ReadFile(checkPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "codegen: read %s: %v\n", checkPath, err)
			os.Exit(1)
		}
		if !bytes.Equal(got, expected) {
			fmt.Fprintf(os.Stderr,
				"codegen: %s is stale (regenerate via `go run ./internal/argvallow/codegen -o %s`)\n",
				checkPath, checkPath)
			os.Exit(1)
		}
		return
	}

	if outPath != "" {
		// 0o644 is the conventional mode for source-controlled
		// generated files. The freshness check enforces content;
		// the file mode is incidental.
		if err := os.WriteFile(outPath, expected, 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "codegen: write %s: %v\n", outPath, err)
			os.Exit(1)
		}
		return
	}

	if _, err := os.Stdout.Write(expected); err != nil {
		fmt.Fprintf(os.Stderr, "codegen: write stdout: %v\n", err)
		os.Exit(1)
	}
}

// render produces the §9.12 byte stream for entries. The input must be
// in declaration order (matching default.txt) and have a length that
// fits the cumulative groupBoundaries array — otherwise render returns
// an error rather than emitting a layout that drifts from §9.12.
func render(entries []string) ([]byte, error) {
	if len(entries) == 0 {
		return nil, fmt.Errorf("empty entry list")
	}
	if got, want := len(entries), groupBoundaries[len(groupBoundaries)-1]; got != want {
		return nil, fmt.Errorf("entry count %d does not match §9.12 layout (%d expected); update groupBoundaries", got, want)
	}

	var b bytes.Buffer
	b.WriteString(headerLine1)
	b.WriteByte('\n')
	b.WriteString(headerLine2)
	b.WriteByte('\n')
	b.WriteString(headerLine3)
	b.WriteByte('\n')
	b.WriteString("return {\n")

	start := 0
	for _, end := range groupBoundaries {
		b.WriteString("    ")
		group := make([]string, 0, end-start)
		for _, name := range entries[start:end] {
			group = append(group, fmt.Sprintf("%q", name))
		}
		b.WriteString(strings.Join(group, ", "))
		b.WriteString(",\n")
		start = end
	}

	b.WriteString("}\n")
	return b.Bytes(), nil
}
