package main

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/Grady-Saccullo/wezsesh/internal/argvallow"
)

// expectedLua is the §9.12 byte stream verbatim. Any drift here is a
// spec violation — T-605 wires this same expectation into the CI
// freshness gate (`go run ./internal/argvallow/codegen --check`).
const expectedLua = `-- AUTOGENERATED by ` + "`go run ./internal/argvallow/codegen`" + `.
-- Source: internal/argvallow/default.txt
-- DO NOT EDIT BY HAND.
return {
    "sh", "bash", "zsh", "fish", "dash", "ksh",
    "nvim", "vim", "vi", "emacs", "nano", "helix", "hx",
    "less", "more", "man", "info",
    "git", "jj", "lazygit", "tig",
    "python", "python3", "ipython", "node", "ruby", "irb", "lua",
    "htop", "btop", "top", "k9s", "lazydocker",
    "tmux", "screen",
}
`

func TestRender_ByteEqual_Spec912(t *testing.T) {
	got, err := render(argvallow.Default())
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	if string(got) != expectedLua {
		t.Fatalf("render() drifted from §9.12\n--- got (%d bytes) ---\n%s\n--- want (%d bytes) ---\n%s",
			len(got), got, len(expectedLua), expectedLua)
	}
}

func TestRender_TrailingNewline(t *testing.T) {
	got, err := render(argvallow.Default())
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	if !bytes.HasSuffix(got, []byte("}\n")) {
		t.Errorf("render output missing trailing newline; got tail=%q", got[max(0, len(got)-8):])
	}
}

func TestRender_RejectsWrongLength(t *testing.T) {
	if _, err := render(nil); err == nil {
		t.Error("render(nil) returned no error; want error on empty input")
	}
	short := []string{"sh", "bash"}
	if _, err := render(short); err == nil {
		t.Error("render(short) returned no error; want error on layout mismatch")
	}
}

// TestRender_Deterministic asserts repeated calls produce identical
// bytes — no map-iteration order leakage, no time.Now embeds, etc.
func TestRender_Deterministic(t *testing.T) {
	a, err := render(argvallow.Default())
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	for i := 0; i < 10; i++ {
		b, err := render(argvallow.Default())
		if err != nil {
			t.Fatalf("render iter %d: %v", i, err)
		}
		if !bytes.Equal(a, b) {
			t.Fatalf("render output varies between calls (iter %d)", i)
		}
	}
}

// TestCLI_StdoutAndCheckMode exercises the actual `go run` entry to
// confirm the CLI surface T-605 will wire (-o + --check). It compiles
// the codegen binary and invokes it both ways.
func TestCLI_StdoutAndCheckMode(t *testing.T) {
	tmpDir := t.TempDir()
	bin := filepath.Join(tmpDir, "codegen")
	build := exec.Command("go", "build", "-o", bin, ".")
	build.Stderr = os.Stderr
	if err := build.Run(); err != nil {
		t.Fatalf("go build codegen: %v", err)
	}

	// Stdout mode.
	stdoutCmd := exec.Command(bin)
	out, err := stdoutCmd.Output()
	if err != nil {
		t.Fatalf("codegen (stdout): %v", err)
	}
	if string(out) != expectedLua {
		t.Fatalf("stdout output mismatched §9.12\n got: %q\nwant: %q", out, expectedLua)
	}

	// -o mode.
	target := filepath.Join(tmpDir, "default_allowlist.lua")
	writeCmd := exec.Command(bin, "-o", target)
	writeCmd.Stderr = os.Stderr
	if err := writeCmd.Run(); err != nil {
		t.Fatalf("codegen -o: %v", err)
	}
	got, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("read %s: %v", target, err)
	}
	if string(got) != expectedLua {
		t.Fatalf("-o output mismatched §9.12\n got: %q\nwant: %q", got, expectedLua)
	}

	// --check mode (passing).
	checkCmd := exec.Command(bin, "--check", target)
	if err := checkCmd.Run(); err != nil {
		t.Fatalf("--check on freshly written file should pass; got: %v", err)
	}

	// --check mode (failing).
	stale := filepath.Join(tmpDir, "stale.lua")
	if err := os.WriteFile(stale, []byte("-- stale\n"), 0o644); err != nil {
		t.Fatalf("write stale: %v", err)
	}
	failCmd := exec.Command(bin, "--check", stale)
	if err := failCmd.Run(); err == nil {
		t.Error("--check on stale file should exit non-zero; got nil error")
	}
}
